spring:
  application:
    name: config
  profiles:
    active: dev

---
server:
  port: 8187
spring:
  profiles: dev
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: sangoes
    password: Sangoes123456
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sangoes/sangoes-cloud-config.git
#          username:
#          password:
          default-label: ${spring.profiles}
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://sangoes:Sangoes123456@localhost:8671/eureka
    registry-fetch-interval-seconds: 10
    enabled: true
    register-with-eureka: true
    fetch-registry: true